name: metasurface-depth
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pytorch
  - torchvision
  - matplotlib
  - pyyaml
  - h5py
  - tqdm
  - pillow
  - scikit-image
  - pip
  - pip:
      - einops
      - opencv-python
      - torchoptics
      - waveprop
